name: Save PT ninja build cache
description: Save pytorch build/ incremental cache

inputs:
  pt-src:
    description: pytorch source root
    required: true
  cache-primary-key:
    description: cache-primary-key from A02.pt-ninja-cache-restore
    required: true

runs:
  using: composite
  steps:
    - name: Save ninja incremental build cache
      if: inputs.cache-primary-key != ''
      uses: actions/cache/save@v6
      with:
        path: ${{ inputs.pt-src }}\build
        key: ${{ inputs.cache-primary-key }}
