name: Save PT ninja build cache
description: 保存 PyTorch build/ 增量缓存

inputs:
  pt-src:
    description: PyTorch 源码根目录
    required: true
  cache-primary-key:
    description: A02.pt-ninja-cache-restore 输出的 cache-primary-key
    required: true

runs:
  using: composite
  steps:
    - name: Save ninja incremental build cache
      if: inputs.cache-primary-key != ''
      uses: actions/cache/save@v6
      with:
        path: ${{ inputs.pt-src }}\build
        key: ${{ inputs.cache-primary-key }}
